from __future__ import annotations

import re

from tilelang.backend.device_codegen import global_func_device_codegen

_raw_build_opencl = global_func_device_codegen("target.build.opencl")


class _SourcePatchedModule:
    def __init__(self, mod, source: str):
        self._mod = mod
        self._source = source

    def inspect_source(self, *args, **kwargs):
        return self._source

    def __getattr__(self, name):
        return getattr(self._mod, name)


def _patch_opencl_private_accumulators(source: str) -> str:
    """Keep small private OpenCL accumulator arrays in vector registers.

    TVM's legacy OpenCL printer emits TileLang ``local.fragment`` buffers as C
    private arrays (e.g. ``float acc[64]``).  Adreno's OpenCL compiler does not
    reliably scalar-replace such arrays in the texture GEMM inner loop, so the
    generated kernel spills the accumulator tile.  This OpenCL-only source fixup
    rewrites the recognized fully-unrolled accumulator array into ``float8``
    vector variables while leaving the TIR and non-OpenCL backends untouched.
    """

    original_source = source
    patched_accumulators: set[str] = set()

    def repl_decl(match: re.Match[str]) -> str:
        indent = match.group(1)
        name = match.group(2)
        n = int(match.group(3))
        if n <= 1 or n % 8 != 0 or n > 128:
            return match.group(0)
        patched_accumulators.add(name)
        return "\n".join(f"{indent}float8 {name}_{i} = (float8)(0.000000e+00f);" for i in range(n // 8))

    # Only patch arrays whose base name starts with "acc".  Other private arrays
    # such as avec[32] may still use variable indices (kk) and are not safe to
    # vector-registerize by textual replacement.
    source = re.sub(r"(?m)^(\s*)float\s+(acc\w*)\[(\d+)\];\s*$", repl_decl, source)

    def repl_acc(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in patched_accumulators:
            return match.group(0)
        idx = int(match.group(2))
        return f"{name}_{idx // 8}.s{idx % 8}"

    source = re.sub(r"\b(acc\w*)\[(\d+)\]", repl_acc, source)

    # Safety: if any access to a patched accumulator survived with a
    # non-constant index (e.g. acc[kk]), the array declaration is gone but the
    # reference remains, producing uncompilable source.  Revert everything in
    # that case.
    for name in patched_accumulators:
        if re.search(rf"\b{re.escape(name)}\[", source):
            return original_source

    # Legacy OpenCL vector element extraction is printed as address-taking of a
    # half4 temporary, e.g. ((half*)&v_)[2].  That address escape is another
    # Adreno SROA blocker.  Use OpenCL swizzles instead.
    source = re.sub(r"\(\(half\s*\*\)&([A-Za-z_]\w*)\)\[(\d)\]",
                    lambda m: f"{m.group(1)}.s{m.group(2)}", source)
    return source


def _patch_opencl_gemm_nt_fragment_8x8(source: str) -> str:
    """Recognize direct-global 8x8/thread GEMM_NT fragment output.

    The OpenCL printer emits the fully-unrolled fragment accumulator as scalar
    swizzle updates after ``_patch_opencl_private_accumulators``.  That is
    register-resident, but it still issues 64 scalar half loads per K.  For the
    canonical GEMM_NT fragment kernel generated by examples/opencl/kernels/
    gemm_nt.py, rewrite the scalar body to the same register/vector-load form a
    human would write: eight float8 accumulator rows, A/B read as half4 along K,
    and vector stores for C.  This remains an OpenCL codegen peephole for a pure
    TileLang IR kernel; it is not an example-side source escape hatch.
    """

    if "__local" in source or "barrier(" in source or "image" in source:
        return source
    if "float8 acc_0" not in source or "float8 acc_7" not in source:
        return source
    if "__kernel void gemm_nt_kernel_kernel(__global half* restrict A, __global half* restrict B, __global half* restrict C)" not in source:
        return source

    m_ko = re.search(r"for \(int ko = 0; ko < (\d+); \+\+ko\)", source)
    m_kk = re.search(r"for \(int kk = 0; kk < (\d+); \+\+kk\)", source)
    m_gy_a = re.search(r"get_group_id\(1\)\)\) \* (\d+)\)", source)
    m_gx_b = re.search(r"get_group_id\(0\)\)\) \* (\d+)\)", source)
    m_gy_c = re.search(r"C\[\(\(\(\(\(convert_int\(get_group_id\(1\)\)\) \* (\d+)\)", source)
    m_gx_c = re.search(r"\+ \(\(convert_int\(get_group_id\(0\)\)\) \* (\d+)\)\)", source)
    if not (m_ko and m_kk and m_gy_a and m_gx_b and m_gy_c and m_gx_c):
        return source

    ko_extent = int(m_ko.group(1))
    bk = int(m_kk.group(1))
    K = ko_extent * bk
    if K <= 0 or K % 4:
        return source
    bm = int(m_gy_a.group(1)) // K
    bn = int(m_gx_b.group(1)) // K
    c_stride = int(m_gy_c.group(1))
    bn_c = int(m_gx_c.group(1))
    if bm <= 0 or bn <= 0 or bm % 8 or bn % 8 or bn != bn_c or c_stride % bm:
        return source
    N = c_stride // bm
    tiles_n = bn // 8

    header = source[: source.find("{") + 1]
    lines = [header]
    lines.append(f"\n  const int lid = convert_int(get_local_id(0));")
    lines.append(f"\n  const int bx = convert_int(get_group_id(0));")
    lines.append(f"\n  const int by = convert_int(get_group_id(1));")
    lines.append(f"\n  const int tm = lid / {tiles_n};")
    lines.append(f"\n  const int tn = lid - tm * {tiles_n};")
    lines.append(f"\n  const int r0 = by * {bm} + tm * 8;")
    lines.append(f"\n  const int c0 = bx * {bn} + tn * 8;")
    for i in range(8):
        lines.append(f"\n  float8 acc_{i} = (float8)(0.0f);")
    lines.append(f"\n  for (int pos = 0; pos < {K}; pos += 4) {{")
    for i in range(8):
        lines.append(f"\n    const float4 a{i} = convert_float4(vload4(0, A + (size_t)(r0 + {i}) * {K} + pos));")
    for j in range(8):
        lines.append(f"\n    const float4 b{j} = convert_float4(vload4(0, B + (size_t)(c0 + {j}) * {K} + pos));")
    for i in range(8):
        for lane, comp in enumerate("xyzw"):
            bvec = ", ".join(f"b{j}.{comp}" for j in range(8))
            lines.append(f"\n    acc_{i} += (float8)(a{i}.{comp}) * (float8)({bvec});")
    lines.append("\n  }")
    for i in range(8):
        lines.append(f"\n  vstore8(convert_half8(acc_{i}), 0, C + (size_t)(r0 + {i}) * {N} + c0);")
    lines.append("\n}\n")
    return "".join(lines)


def build_opencl(mod, target):
    built = _raw_build_opencl(mod, target)
    source = built.inspect_source()
    patched = _patch_opencl_private_accumulators(source)
    patched = _patch_opencl_gemm_nt_fragment_8x8(patched)
    if patched == source:
        return built
    return _SourcePatchedModule(built, patched)
