"""Hexagon-v2 source codegen prototype for GEMM_NT.

This is a source-producing Phase-1 bridge: it does not touch the production
``tilelang.hexagon`` statement emitter.  The generated DSP C uses the existing
runtime support layer for VTCM copies/AH staging/writeback, but emits the HMX
compute core as an explicit deep-chain inline-asm intrinsic.
"""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
from textwrap import dedent

import tvm
import tvm_ffi
from tvm import IRModule
from tvm.target import Target

from .target import DEFAULT_TARGET


@dataclass(frozen=True)
class GemmNTConfig:
    symbol: str = "attnops_tl_gemm_nt_v2"
    block_m: int = 32
    block_n: int = 1024
    kmax: int = 4096
    wa_max: int = 5632 * 1024


def _source_module(source: str, symbols: list[str]):
    create = tvm.ffi.get_global_func("runtime.CSourceModuleCreate")
    return create(source, "c", symbols, [])


def _validate_gemm_shape(m: int, n: int, k: int, cfg: GemmNTConfig) -> None:
    if m <= 0 or n <= 0 or k <= 0:
        raise ValueError("M/N/K must be positive")
    if m % cfg.block_m or n % 256 or k % 64:
        raise ValueError("Hexagon-v2 GEMM requires M%32==0, N%256==0, K%64==0")
    if k > cfg.kmax:
        raise ValueError(f"K={k} exceeds Phase-1 kmax={cfg.kmax}")
    if DEFAULT_TARGET.hmx_chain_max != 32:
        raise ValueError("Phase-1 codegen assumes HMX chain_max=32")


def _int_dim(dim) -> int | None:
    if isinstance(dim, int):
        return int(dim)
    if hasattr(dim, "value"):
        return int(dim.value)
    return None


def _infer_gemm_shape(mod: IRModule) -> tuple[int, int, int] | None:
    """Infer ``M,N,K`` from the original GEMM function buffers when present."""

    for func in mod.functions.values():
        buffer_map = getattr(func, "buffer_map", None)
        if not buffer_map or len(buffer_map) < 3:
            continue
        bufs = [buffer_map[param] for param in func.params if param in buffer_map]
        if len(bufs) < 3:
            continue
        a_shape = [_int_dim(x) for x in bufs[0].shape]
        b_shape = [_int_dim(x) for x in bufs[1].shape]
        c_shape = [_int_dim(x) for x in bufs[2].shape]
        if len(a_shape) == len(b_shape) == len(c_shape) == 2 and None not in a_shape + b_shape + c_shape:
            m, k = a_shape
            n, kb = b_shape
            cm, cn = c_shape
            if k == kb and m == cm and n == cn:
                return int(m), int(n), int(k)
    return None


def emit_gemm_nt_c(m: int, n: int, k: int, *, cfg: GemmNTConfig | None = None) -> str:
    """Emit deterministic DSP-side C for ``C[M,N]=A[M,K]@B[N,K]^T``.

    ``B`` is expected in the same WH-preconverted panel image used by the legacy
    TileLang GEMM skel path.  The vertical slicing axis is N; runtime chooses a
    panel width ``NP`` in ``{1024,512,256}`` that divides the requested slice.
    """

    cfg = cfg or GemmNTConfig()
    _validate_gemm_shape(m, n, k, cfg)

    return dedent(
        f"""
        // Generated by tilelang.hexagon_v2.codegen: GEMM_NT Phase-1 deep-chain.
        // HMX asm markers: mxclracc.hf, mxmem:deep, mxmem2, :after.hf.
        // Deterministic source; do not hand edit generated copies.
        #include <stdint.h>
        #include <stddef.h>
        #include <string.h>
        #include "attnops.h"
        #include "HAP_perf.h"
        #include <hexagon_types.h>
        #include <hvx_hexagon_protos.h>
        #include "hexagon_rt.h"

        typedef hrt_f16 f16;
        typedef hrt_f32 f32;

        #define HV2_GM_TILE HRT_TILE_BYTES
        #define HV2_GM_KMAX {cfg.kmax}
        #define HV2_GM_BLOCK_N {cfg.block_n}
        #define HV2_GM_LIN  (0)
        #define HV2_GM_ACT  (HV2_GM_LIN + HV2_GM_KMAX * 64)
        #define HV2_GM_WA   (HV2_GM_ACT + HV2_GM_KMAX * 64)
        #define HV2_GM_WA_MAX ((size_t){cfg.wa_max})
        #define HV2_GM_OUT  (HV2_GM_WA + HV2_GM_WA_MAX)
        #define HV2_GM_SCALE (HV2_GM_OUT + 2 * HV2_GM_TILE)
        #define HV2_GM_END  (HV2_GM_SCALE + 256)

        static inline void hv2_hmx_acc_clear(void) {{
            asm volatile("mxclracc.hf\\n" ::: "memory");
        }}

        static inline void hv2_hmx_mma_deep(const void *act, const void *wt, uint32_t range) {{
            asm volatile(
                "{{\\n"
                "    activation.hf = mxmem(%1, %0):deep\\n"
                "    weight.hf = mxmem(%2, %0)\\n"
                "}}\\n"
                : : "r"(range), "r"((uint32_t)(uintptr_t)act), "r"((uint32_t)(uintptr_t)wt) : "memory");
        }}

        static inline void hv2_hmx_set_bias(const void *scales) {{
            asm volatile("bias = mxmem2(%0)\\n" : : "r"((uint32_t)(uintptr_t)scales) : "memory");
        }}

        static inline void hv2_hmx_store_after(void *out) {{
            asm volatile("mxmem(%0, %1):after.hf = acc\\n"
                         : : "r"((uint32_t)(uintptr_t)out), "r"(0) : "memory");
        }}

        static inline void hv2_hmx_mma_deep_split(uint8_t *V, size_t ah_off, size_t wh_off, int kt) {{
            int done = 0;
            while (done < kt) {{
                int n = kt - done;
                if (n > 32) n = 32;
                uint32_t range = (uint32_t)(n * HRT_TILE_BYTES - 1);
                hv2_hmx_mma_deep(V + ah_off + (size_t)done * HRT_TILE_BYTES,
                                 V + wh_off + (size_t)done * HRT_TILE_BYTES,
                                 range);
                done += n;
            }}
        }}

        static inline void hv2_hmx_init_scale(uint8_t *V) {{
            HVX_Vector one = Q6_Vh_vsplat_R(0x3c00);
            HVX_Vector zero = Q6_V_vzero();
            *(HVX_Vector *)(V + HV2_GM_SCALE) = one;
            *(HVX_Vector *)(V + HV2_GM_SCALE + 128) = zero;
            hv2_hmx_set_bias(V + HV2_GM_SCALE);
        }}

        int {cfg.symbol}(remote_handle64 h, unsigned char *slab, int slabLen,
                         unsigned char *w, int wLen, int M, int N, int K, int abl) {{
            (void)h;
            if (!HRT_VTCM_READY()) return -3;
            if (M <= 0 || N <= 0 || K <= 0 || M % 32 || N % 256 || K % 64 || K > HV2_GM_KMAX) return -2;
            if ((size_t)HV2_GM_END > HRT_VTCM_SIZE()) return -4;
            int NP = 0;
            for (int t = HV2_GM_BLOCK_N; t >= 256; t >>= 1)
                if (N % t == 0 && (size_t)K * t * 2 <= HV2_GM_WA_MAX) {{ NP = t; break; }}
            if (!NP) return -2;
            size_t x_sz = (size_t)M * K * 2;
            size_t c_off = HRT_ALIGN128(x_sz);
            size_t c_sz = (size_t)M * N * 2;
            size_t prof_off = HRT_ALIGN128(c_off + c_sz);
            if ((size_t)slabLen < prof_off + 20) return -1;
            if ((size_t)wLen < (size_t)K * N * 2) return -1;
            const f16 *A = (const f16 *)slab;
            f16 *C = (f16 *)(slab + c_off);
            HRT_PROF_DECL(prof, slab, prof_off);
            HRT_PROF_CLEAR(prof, 20);

            uint8_t *V = HRT_VTCM_BASE();
            int kt = K / 32, nct = NP / 32;
            uint64_t t0, tt = HAP_perf_get_qtimer_count();
            for (int bx = 0; bx < N / NP; bx++) {{
                t0 = HAP_perf_get_qtimer_count();
                if (!(abl & 1))
                    hrt_copy_pooled(V + HV2_GM_WA, (const uint8_t *)w + (size_t)bx * nct * kt * HRT_TILE_BYTES,
                        (size_t)nct * kt * HRT_TILE_BYTES);
                prof[0] += (int32_t)(HAP_perf_get_qtimer_count() - t0);
                for (int m0 = 0; m0 < M / 32; m0++) {{
                    t0 = HAP_perf_get_qtimer_count();
                    if (!(abl & 2)) {{
                        hrt_copy_128_dcfetch(V + HV2_GM_LIN, (const uint8_t *)(A + (size_t)m0 * 32 * K), (size_t)32 * K * 2);
                        hrt_mask_init();
                        hrt_stage_act_hvx(V + HV2_GM_LIN, V + HV2_GM_ACT, K, kt, HRT_TILE_BYTES);
                    }}
                    prof[1] += (int32_t)(HAP_perf_get_qtimer_count() - t0);
                    for (int c2 = 0; c2 < nct; c2++) {{
                        t0 = HAP_perf_get_qtimer_count();
                        if (!(abl & 4)) {{
                            int e = hrt_acc_clear_f16();
                            if (e) return e;
                            hv2_hmx_mma_deep_split(V, HV2_GM_ACT,
                                HV2_GM_WA + (size_t)c2 * kt * HRT_TILE_BYTES, kt);
                            if (!(abl & 16)) {{
                                e = hrt_acc_read_f16(V, g_v.CFG, HV2_GM_OUT + (size_t)(c2 & 1) * HRT_TILE_BYTES);
                                if (e) return e;
                            }}
                        }}
                        prof[2] += (int32_t)(HAP_perf_get_qtimer_count() - t0);
                        t0 = HAP_perf_get_qtimer_count();
                        if (!(abl & 8) && (c2 & 1)) {{
                            int ncol = bx * NP + (c2 - 1) * 32;
                            hrt_mask_init();
                            hrt_unperm_pair_hvx(V + HV2_GM_OUT, V + HV2_GM_OUT + HRT_TILE_BYTES, C + (size_t)(m0 * 32) * N + ncol, N);
                        }}
                        prof[3] += (int32_t)(HAP_perf_get_qtimer_count() - t0);
                    }}
                }}
            }}
            prof[4] = (int32_t)(HAP_perf_get_qtimer_count() - tt);
            return 0;
        }}
        """
    ).lstrip()


def build_hexagon_v2_without_compile(mod: IRModule, target: Target):
    """TVM global builder hook for Phase-0 registration smoke tests.

    The generic builder cannot infer GEMM shapes from arbitrary lowered TIR yet;
    callers should set ``TILELANG_HEXAGON_V2_M/N/K`` for this skeleton entry or
    use :func:`emit_gemm_nt_c` directly.
    """

    inferred = _infer_gemm_shape(mod)
    dm, dn, dk = inferred or (1024, 12288, 2560)
    m = int(os.environ.get("TILELANG_HEXAGON_V2_M", str(dm)))
    n = int(os.environ.get("TILELANG_HEXAGON_V2_N", str(dn)))
    k = int(os.environ.get("TILELANG_HEXAGON_V2_K", str(dk)))
    symbol = os.environ.get("TILELANG_HEXAGON_V2_SYMBOL", "attnops_tl_gemm_nt_v2")
    source = emit_gemm_nt_c(m, n, k, cfg=GemmNTConfig(symbol=symbol))
    if out := os.environ.get("TILELANG_HEXAGON_V2_EMIT_C"):
        path = Path(out)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
    return _source_module(source, [symbol])


tvm_ffi.register_global_func(
    "target.build.tilelang_hexagon_v2_without_compile",
    f=build_hexagon_v2_without_compile,
    override=True,
)
